### ISSUE TITLE
Can't open Example Project

### ISSUE THREAD

**Issue by RoostOne** [stereolabs/zed-livelink#12]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

![image](https://user-images.githubusercontent.com/45451399/230736097-d85e4e41-4bb4-4472-ac12-66b17bf84cd3.png)
![image](https://user-images.githubusercontent.com/45451399/230736126-84523018-0c85-4a54-8f59-f1ec596fc209.png)

### Steps to Reproduce

- downloaded the repository 
- i use unreal 5.1 from the epic launcher. 
- launch from the explorer selecting the version
- 
![image](https://user-images.githubusercontent.com/45451399/230736186-f8a12277-8808-4331-a22f-6eb7f0c36935.png)

- and than i get the error message

### Expected Result

the project should open

### Actual Result

the error message from the description

### ZED Camera model

ZED

### Environment

```shell
Windows 
Ryzen 
UE 5.1
```

### Anything else?

The documentation https://www.stereolabs.com/docs/livelink/ is very vague and has no troubleshooting. It says you can open the project. 
Also it is called Zed Live Link plugin but does it need to be installed with the Unreal Version i open it?

**Comment by Bvallon-sl** [comment]
Hi,

Did you try to build the project from sources as said in the error message?

**Comment by RoostOne** [comment]
Hi, 

I googled it but found no real solution. I was able to solve it with the generate Visual Studio Files 
![image](https://user-images.githubusercontent.com/45451399/231388729-ac874a36-873d-4abb-b5b4-ae403e006e59.png)

and then build the zed livelink part. 
Could you please include the ddls?
