### ISSUE TITLE
ZEDLiveLinkFusion not work.

### ISSUE THREAD

**Issue by darkladen** [stereolabs/zed-livelink#16]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

When run file ZEDLiveLinkFusion(Windows) this end without error but to the end log this say "Empty File" ? 

Thanks.
*** Init LOG ***
resolution : HD1080
fps : 30
depth_mode : ULTRA
detection_model : HUMAN BODY ACCURATE
body_format : BODY_38
body_selection : FULL
confidence : 40
max_range : -1
Loading config file ...
Cameras calibration filename :
output_performance_metrics : 1
verbose : 0
skeleton_minimm_allowed_keypoints : 8
skeleton_minimum_allowed_camera : -1
skeleton_smoothing : 0
Empty File
*** End LOG ***

### Steps to Reproduce

1. From shell windows (cmd/powershell)
2. Run file "ZEDLiveLinkFusion.exe" (the Zed 2 cam connected)
3. This load and close immediately

### Expected Result

That works !!

### Actual Result

Script Fusion version not work but Mono version work 100%

### ZED Camera model

ZED2

### Environment

```shell
OS: Windows 11
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz 2.20 GHz
GPU: GTX 1050
ZED SDK 4.0.2
```

**Comment by SLJLMacarit** [comment]
Hello @darkladen ,
It's indeed lacking a proper explanatory error, but it seems that you did not set the [`json_config_filename`](https://www.stereolabs.com/docs/livelink/#adjust-zed-sdk-parameters-1) path to the calibration file of the camera. You can generate it using [ZED360](https://www.stereolabs.com/docs/fusion/zed360/).

Best,
Jean-Loup

**Comment by darkladen** [comment]
Hello, sorry for the delay in replying.

Yes, now is working beautiful. Is sure that Im not so explicit in my info but in summary, the problem is I just didn't have the calibration file but since i didn't see that info explained anywehere, i figured it should be used the same as ZEDLIveLinkMono.

Anyway thanks !!!
