### ISSUE TITLE
Build not work detecting Providers.

### ISSUE THREAD

**Issue by darkladen** [stereolabs/zed-livelink#19]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

When i build my project (windows) this crash when try detecting providers. In Editor Mode work 100% but when i make the build this not work.

Any solution ?

Thanks.

### Steps to Reproduce

1.- Using Unreal Proyect into zed-livelink-main.
2.- Add/make the necessary modifications.
3.- Compile.
4.- Test the built package
5.- Crash when trying to detect providers

### Expected Result

Crash when trying to detect providers.
If I disable the detection of providers, the package works.

### Actual Result

Crash when trying to detect providers

### ZED Camera model

ZED2

### Environment

```shell
OS: Windows 10
CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
GPU: NVIDIA GeForce RTX 2080
Zed SDK Version: v.4.0.4
```

**Comment by darkladen** [comment]
Hellooo !!!! Anyone know how to resolv this problem ?

**Comment by Bvallon-sl** [comment]
Hi,

Can you confirm you are using livelink v4.0.4 ? you need to use the same version as the ZED SDK.

**Comment by darkladen** [comment]
The truth is that i dont know how to see the version but i think that this can not be the 4.0.4 version. Naw i download the last version but i need update too the SDK to last version(4.0.5) ?

**Comment by Bvallon-sl** [comment]
yes the versions need to match even through the program should not crash without logging anything. That's something we need to improve for the next versions.

**Comment by darkladen** [comment]
Hello again, im using all (project and ZDK) with the 4.0.5 version. im still having problems to compile UE5 project. The project compile end fine(shipping package) but when i run this build, i receive a "Fatal error". If I compile in "development package mode" this work fine and although it does not give me errors when I run this compilation, also connect to livelink.

I need help, thanks.
