### ISSUE TITLE
Fusion not working

### ISSUE THREAD

**Issue by ccjake** [stereolabs/zed-livelink#21]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

- I currently have two zed 2i's and wanted to try out the fusion feature but it crashed right away after click ZEDLiveLinkFusion.exe. Is there a workaround for this? I have tried both zed sdk 4.0.5 and 4.0.6 without success. By the way, mono works fine both on 4.0.5 or  4.0.6.

### Steps to Reproduce

1.Plug in two zed 2i cameras via usb3.0 ports
2.Click [ZEDLiveLinkFusion.exe](https://github.com/stereolabs/zed-livelink/blob/main/zed-livelink-fusion/Release/win64/ZEDLiveLinkFusion.exe)
3. ZEDLiveLinkFusion.exe Crashed.

### Expected Result

ZEDLiveLinkFusion.exe should keep runing.

### Actual Result

ZEDLiveLinkFusion.exe crashes immediately.

### ZED Camera model

ZED

### Environment

```shell
OP: Win10,
CPU: Intel 12700,
GPU: RTX 4600
```

**Comment by SLJLMacarit** [comment]
Hi @ccjake,

To use the Fusion, you must first generate a configuration file using [ZED360](https://www.stereolabs.com/docs/fusion/zed360/) and then give the path to this file to the Live Link config file (see the [documentation](https://www.stereolabs.com/docs/livelink/livelink-ue5/#using-the-live-link-sample-with-the-fusion-api).

I see the readme is a bit outdated, please refer to the documentation for now, we'll update it soon.
