### ISSUE TITLE
livelink-mono built from source does not appear as a LiveLink Source in editor.

### ISSUE THREAD

**Issue by ssav7912** [stereolabs/zed-livelink#23]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Cloning this repository, building the livelink-mono program from source in Development_Program mode and running the built binary will not show up as a Livelink source in the corresponding unreal project. If however I run the binary provided in the `Releases/` folder, this will appear as a source in Unreal. 

### Steps to Reproduce

1. Clone repository into UE5.3.2 source tree (Programs)
2. Build the zed-livelink-mono project with the Development_Program configuration (although this doesn't work across any configuration)
3. Run the binary. Camera will successfully open, and will arrive at the 'waiting for connection' message:
```Trying to load default config file 'ZEDLiveLinkConfig.json'
Loading config file ...
resolution : HD720
fps : 60
depth_mode : ULTRA
grab_compute_capping_fps : 0
enable_image_validity_check : 0
enable_pose_smoothing : 1
enable_area_memory : 0
enable_body_tracking_module : 1
detection_model : HUMAN BODY ACCURATE
body_format : BODY_38
body_selection : FULL
confidence : 50
max_range : -1
minimum_keypoints_threshold : -1
skeleton_smoothing : 0.2
Input : USB ID : 0
Starting ZEDLiveLink tool
Opening camera...
[2024-03-20 05:34:25 UTC][ZED][INFO] Logging level INFO
[2024-03-20 05:34:25 UTC][ZED][INFO] [Init]  Depth mode: ULTRA
[2024-03-20 05:34:26 UTC][ZED][INFO] [Init]  Camera successfully opened.
[2024-03-20 05:34:26 UTC][ZED][INFO] [Init]  Sensors FW version: 777
[2024-03-20 05:34:26 UTC][ZED][INFO] [Init]  Camera FW version: 1523
[2024-03-20 05:34:26 UTC][ZED][INFO] [Init]  Video mode: HD720@60
[2024-03-20 05:34:26 UTC][ZED][INFO] [Init]  Serial Number: S/N 32516791
LogPaths: Warning: No paths for game localization data were specifed in the game configuration.
LogInit: Warning: No paths for engine localization data were specifed in the engine configuration.
LogUdpMessaging: Display: Added local interface '192.168.148.185' to multicast group '230.0.0.1:6666'
LogUdpMessaging: Display: Added local interface '172.30.64.1' to multicast group '230.0.0.1:6666'
Waiting for connection...
```
4. Attempt to find the camera as a source in Unreal's Livelink message bus sources window. Will not appear.
5. Close the running instance and start the binary provided in the `Releases/` folder, shipped with this repository. 
6. Attempt to find the camera as a source in Unreal's Livelikn message bus sources window. Source will appear and will work correctly.
7. Log messages more or less equal between the 2 versions. Shipped binary log below:
```
Trying to load default config file 'ZEDLiveLinkConfig.json'
Loading config file ...
resolution : HD720
fps : 30
depth_mode : ULTRA
grab_compute_capping_fps : 0
enable_image_validity_check : 0
enable_pose_smoothing : 1
enable_area_memory : 0
enable_body_tracking_module : 1
detection_model : HUMAN BODY ACCURATE
body_format : BODY_38
body_selection : FULL
confidence : 50
max_range : -1
minimum_keypoints_threshold : -1
skeleton_smoothing : 0.2
Input : SVO ZED2_HD2K_Runners_H264.svo
Starting ZEDLiveLink tool
Opening camera...
[2024-03-20 04:35:20 UTC][ZED][INFO] Logging level INFO
[2024-03-20 04:35:20 UTC][ZED][INFO] [Init]  Depth mode: ULTRA
[2024-03-20 04:35:20 UTC][ZED][INFO] [Init]  Serial Number: S/N 24605000
LogPaths: Warning: No paths for game localization data were specifed in the game configuration.
LogInit: Warning: No paths for engine localization data were specifed in the engine configuration.
LogUdpMessaging: Display: Added local interface '192.168.148.185' to multicast group '230.0.0.1:6666'
LogUdpMessaging: Display: Added local interface '172.30.64.1' to multicast group '230.0.0.1:6666'
Waiting for connection...
ZEDLiveLink is connected
ZED Camera added : 24605000
```

### Expected Result

Version built from source should appear as a livelink source in the unreal editor. In essence, cloning this repository and making no changes should produce a binary that behaves identically to the binary shipped in `Releases/`.  

### Actual Result

binary built from source will not appear as a Livelink source in the unreal editor. 

I have tried building in every configuration (Debug_Program through to Shipping_Program). I have tried adding extra verbose Logging to both the unreal editor and the livelink-mono program (via `-LogCmds="LogUdpMessaging veryVerbose, LogLiveLink veryVerbose")`, which produces nothing useful. I have tried stepping through the livelink-mono program in a debugger, which does not produce any apparent incorrect state. I have tried deleting, recreating, and manually specifying inbound and outbound firewall rules, although this is all running on the same machine. 

### ZED Camera model

ZED

### Environment

```shell
OS: Windows 10 10.0.19045
Unreal Engine 5.3.2 (both Editor & source toolchain. Editor running the livelink demo map is using Epic's shipped binaries)
```

### Anything else?

Attached are verbose logs from zed-livelink-mono:
[ZEDLiveLink.log](https://github.com/stereolabs/zed-livelink/files/14662682/ZEDLiveLink.log)

And from the Unreal Editor:
[ZedLiveLink.log](https://github.com/stereolabs/zed-livelink/files/14662692/ZedLiveLink.log)

**Comment by jiakechong1991** [comment]
It is possible that the livelink has been transformed on UE5.3
